# Kickstart container config file - see https://gitub.com/infracamp/kickstart
# Run ./kickstart.sh to start a development-container for this project
version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-jekyll:unstable"
ports: "80:80;4000:4000;4100:4100"

command:
  build:
    - "jekyll build -s /opt/docs -d /var/www/html"

  run:

  jekyll: |
    jekyll serve -s /opt/docs -d /var/www/html --drafts --livereload --port 4000 --livereload-port 4100 --host 0.0.0.0

  dev:
    - killall jekyll ||  echo "no job"
    - killall vite ||  echo "no job"
    - "D:setsid kick jekyll"
    - "D:vite -c vite.config.demo.ts build --watch"

  init-workspaces:
    - "mkdir -p workspaces"
    - "git -C ./workspaces/ clone git@github.com:nextrap/nextrap-monorepo.git"
    - "git -C ./workspaces/ clone git@github.com:trunkjs/tj-alpha.git"
    - "npm install"

  update:
    - "npm update"
    - "webpack build"

  killall:
    - killall jekyll
