version: "3.8"
services:
    # This service will be available as: project_name_some_service
    schiller:
        image: ghcr.io/leuffen/schiller:unstable
        secrets:
            - open_ai
        ports:
            -   "5000:80"
        volumes:
            - ./:/data

## Use Secrets already existing
secrets:
    open_ai:
        external: true
